
// BY AMAYA

function loadData(data){
	if(data == "btn1"){
		document.getElementById("pic").src="./images/Individual & Family Plans.png"
		document.getElementById("picdata").innerHTML="CarePro Health Insurance’s Individual & Family Plans are designed to provide comprehensive healthcare coverage for both individuals and their families. These plans ensure access to a wide range of medical services, including preventive care, hospitalizations, specialist consultations, and prescription medications, making it easier to maintain health and well-being without financial strain. For families, the plans offer customizable options to cover dependents, ensuring everyone—from children to adults—can receive quality care. The family plans also include pediatric services like routine check-ups, immunizations, and dental and vision care for children. Additionally, CarePro’s coverage extends to maternity care, mental health services, and management of chronic conditions such as diabetes or asthma. With flexible deductible and premium options, these plans are built to suit varying budgets and healthcare needs, providing families peace of mind with dependable health protection."
	}
	else if(data == "btn2"){
		document.getElementById("pic").src="./images/Group Health Insurance Plans.png"
		document.getElementById("picdata").innerHTML="CarePro Health Insurance offers Group Health Insurance Plans designed to provide healthcare coverage for employees of businesses, organizations, or associations. These plans allow employers to offer their staff a range of health benefits, promoting employee well-being while supporting productivity and job satisfaction. By pooling individuals together under one plan, group health insurance helps to lower premiums and provide more comprehensive coverage options.<br><br>Group Health Insurance Plans include a variety of essential services such as preventive care, hospital stays, specialist consultations, and prescription drug coverage. Employees also benefit from access to mental health support, maternity care, and chronic disease management. Additionally, these plans can be customized with options like dental, vision, and wellness programs, making them a flexible and attractive benefit for employees.<br><br>By offering CarePro’s Group Health Insurance Plans, employers can foster a healthier workplace, improve employee retention, and help workers access the medical services they need. The plans are available in different tiers, allowing businesses to select options that best meet their budget and coverage preferences. With these plans, employers can provide quality healthcare to their teams, ensuring peace of mind and health security."
	}
	else if(data == "btn3"){
		document.getElementById("pic").src="./images/Medicare & Medicaid Plans.png"
		document.getElementById("picdata").innerHTML="CarePro Health Insurance offers Medicare & Medicaid Plans to provide health coverage for eligible individuals, including seniors, people with disabilities, and those with low income. These plans are designed to complement government-sponsored healthcare programs, ensuring that beneficiaries have access to a full range of medical services while minimizing out-of-pocket costs.<br><br>Medicare Plans are available for individuals aged 65 and older, as well as for younger individuals with certain disabilities. CarePro's Medicare Plans provide coverage for hospital stays, doctor visits, preventive services, prescription medications, and more. Additionally, they offer optional benefits like dental, vision, and hearing care, which may not be covered under traditional Medicare. CarePro’s plans aim to simplify healthcare management for seniors by bundling various services into one comprehensive plan.<br><br>Medicaid Plans cater to individuals and families with low income, providing access to essential health services at little to no cost. CarePro works in partnership with state Medicaid programs to offer plans that cover doctor visits, hospital stays, long-term care, and prescription drugs. Special services like maternal and child health care, mental health support, and chronic disease management are also included.<br><br>Both Medicare and Medicaid Plans from CarePro are designed to reduce the financial burden of healthcare while ensuring that individuals have access to high-quality medical services. These plans help beneficiaries get the care they need, whether through regular check-ups, specialist consultations, or emergency medical services, all while adhering to the guidelines and requirements of the respective federal programs."
	}
    else if(data == "btn4"){
		document.getElementById("pic").src="./images/Short-Term Health Insurance.png"
		document.getElementById("picdata").innerHTML="CarePro Health Insurance offers Short-Term Health Insurance plans, designed to provide temporary coverage for individuals during gaps in their regular health insurance. These plans are ideal for those who are between jobs, waiting for other coverage to begin, or in need of immediate coverage for unexpected situations.<br><br>Short-term health insurance offers essential benefits such as doctor visits, emergency care, and hospital stays, though it typically provides limited coverage compared to long-term plans. It’s a flexible, affordable option with the ability to select the length of coverage, which can range from a few months to a year. While these plans don’t cover pre-existing conditions or certain services like maternity care, they provide an essential safety net during transition periods, ensuring access to healthcare when it’s needed most."
	}
    else if(data == "btn5"){
		document.getElementById("pic").src="./images/Emergency Services.png"
		document.getElementById("picdata").innerHTML="CarePro Health Insurance’s Emergency Services coverage is designed to provide immediate medical attention during urgent and life-threatening situations. This coverage ensures that policyholders have access to critical healthcare services, such as emergency room visits, ambulance transportation, and urgent care facilities, without worrying about the high costs typically associated with emergency medical care.<br><br>Whether it's a severe injury, sudden illness, or any other emergency, CarePro’s plans cover the necessary treatments and procedures, including surgeries, diagnostic tests, and medications. The goal is to ensure that individuals receive prompt and effective care in times of crisis, regardless of when or where the emergency occurs. This coverage extends to both in-network and out-of-network facilities, offering flexibility and peace of mind during emergencies.<br><br>CarePro’s Emergency Services coverage helps protect policyholders from unexpected medical bills while ensuring they receive the care they need when it matters most."
	}
    else if(data == "btn6"){
		document.getElementById("pic").src="./images/Elder Citizen Coverage.png"
		document.getElementById("picdata").innerHTML="CarePro Health Insurance offers Elder Citizen Coverage plans specifically designed to meet the unique healthcare needs of seniors. These plans provide comprehensive coverage for individuals aged 65 and older, ensuring they have access to vital medical services while managing the increased healthcare demands that often come with aging. Elder Citizen Coverage includes benefits such as preventive care, hospital stays, specialist consultations, and prescription medications, as well as coverage for chronic disease management, which is crucial for those with long-term health conditions like diabetes, heart disease, or arthritis.<br><br>In addition to core healthcare services, CarePro’s Elder Citizen Coverage also offers optional benefits such as dental, vision, and hearing care, which are often not covered by traditional health insurance or government programs like Medicare. The plans aim to provide peace of mind by reducing the financial burden of healthcare costs for seniors while offering flexible options to suit individual needs and budgets.<br><br>With a focus on accessibility and quality care, CarePro’s Elder Citizen Coverage is designed to help seniors maintain their health and well-being, enabling them to live independently and enjoy their golden years with confidence."
	}
}